# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-09 22:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ta_dash', '0006_auto_20170709_2208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='year_in_school',
            new_name='access',
        ),
    ]
