# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-14 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_dash', '0013_auto_20170713_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='textsubmission',
            name='upload_name',
            field=models.CharField(default='hey', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upload',
            name='upload_name',
            field=models.CharField(default='yup', max_length=200),
            preserve_default=False,
        ),
    ]
