# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-10 23:23
from __future__ import unicode_literals

from django.db import migrations, models
import ta_dash.models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_dash', '0007_auto_20170709_2210'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AddField(
            model_name='textsubmission',
            name='submission_type',
            field=models.CharField(default='text', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upload',
            name='submission_type',
            field=models.CharField(default='upload', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='upload',
            name='upload',
            field=models.FileField(upload_to=ta_dash.models.user_directory_path),
        ),
    ]
