# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-11 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import ta_dash.models
import ta_dash.storage


class Migration(migrations.Migration):

    dependencies = [
        ('ta_dash', '0009_auto_20170711_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='upload',
            field=models.FileField(max_length=255, storage=ta_dash.storage.OverwriteStorage(), upload_to=ta_dash.models.user_directory_path),
        ),
    ]
