# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-12 18:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ta_dash', '0010_auto_20170711_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access', models.CharField(choices=[('TR', 'Teacher'), ('ST', 'Student')], default='ST', max_length=2)),
                ('class_candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta_dash.Class')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.CharField(default='a@gmail.com', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pendingenrollment',
            name='inviter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inviter', to='ta_dash.UserProfile'),
        ),
        migrations.AddField(
            model_name='pendingenrollment',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to='ta_dash.UserProfile'),
        ),
    ]
