# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-13 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_dash', '0012_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_date',
            field=models.CharField(max_length=200),
        ),
    ]
