# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-17 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ta_dash', '0014_auto_20170714_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='S3_Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('associated_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta_dash.Upload')),
            ],
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assignment_name',
            field=models.CharField(max_length=200),
        ),
    ]
